# action.yml
name: 'docker build buildroot'
description: 'Builder for buildroot projects of embedded-CI'
inputs:
  make_target:  # id of input
    description: 'make target of builroot to call'
    required: true
    default: 'help'
  buildroot_path:
    description: 'Path(relative to GITHUB_WORKSPACE) to the root of buildroot'
    required: true
  buildroot_external_path:
    description: 'Path(relative to GITHUB_WORKSPACE) to the buildroot extrernal tree'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_BUILDROOT_PATH: ${{ inputs.buildroot-path }}
    INPUT_BUILDROOT_EXTERNAL_PATH: ${{ inputs.buildroot-external-path }}
  args:
    - ${{ inputs.make_target }}
