# action.yml
name: 'docker buildroot'
description: 'Builder for buildroot projects of embedded-CI'
inputs:
  make_target:  # id of input
    description: 'make target of builroot to call'
    required: true
    default: 'help'
  buildroot_path:
    description: 'Path(relative to GITHUB_WORKSPACE) to the root of buildroot'
    required: true
  buildroot_external_path:
    description: 'Path(relative to GITHUB_WORKSPACE) to the buildroot extrernal tree'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.make_target }}